version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  froide:
    build:
        context: .
        dockerfile: .devcontainer/Dockerfile
    user: vscode
    depends_on:
      - elasticsearch
      - db
    environment:
      - DJANGO_SUPERUSER_PASSWORD=dev
      - DJANGO_SUPERUSER_EMAIL=local-dev@example.com
      - DJANGO_SUPERUSER_USERNAME=dev

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached

      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      # - /var/run/docker.sock:/var/run/docker.sock 

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
 
